language: php
php:
- 7.3
- 7.1
- 7 #!Vorsicht, darf in der Notation nicht von anderen Stages abweichen (z.B. 7 und 7.0)
- nightly
stages:
- test
- ext
- metrics
jobs:
  include:
  - stage: ext
    name: Ext
    php: 7.3
    script: build/scripts/shell/ext.sh
  - stage: ext
    name: Ext
    php: 7.1
    script: build/scripts/shell/ext.sh
  - stage: ext
    name: Ext
    php: 7
    script: build/scripts/shell/ext.sh
  - stage: ext
    name: Ext
    php: nightly
    script: build/scripts/shell/ext.sh
  - stage: metrics
    name: Metrics
    php: 7.3
    script: build/scripts/shell/metrics.sh
  - stage: metrics
    name: Metrics
    php: 7.1
    script: build/scripts/shell/metrics.sh
  - stage: metrics
    name: Metrics
    php: 7
    script: build/scripts/shell/metrics.sh
  - stage: metrics
    name: Metrics
    php: nightly
    script: build/scripts/shell/metrics.sh
matrix:
  allow_failures:
  - php: nightly
notifications:
  on_success: never
  on_failure: change
  #  branches:
  #          except:
  #                - /^nightly-.*$/

addons:
  apt:
    packages:
    - libxml2-utils
    - pdepend
    - phpmd
    - php-xml
    - graphviz
services:
- mysql
install:
- npm install -g jshint
- composer require --dev phpdocumentor/phpdocumentor:@beta
- composer update
- composer install
  #PHPcs
- wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
- wget https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
- chmod +x phpcs.phar phpcbf.phar
- sudo mv phpcs.phar /usr/local/bin/phpcs
- sudo mv phpcbf.phar /usr/local/bin/phpcbf
  #PHPcpd
- wget https://phar.phpunit.de/phpcpd.phar
- chmod +x phpcpd.phar
- sudo mv phpcpd.phar /usr/local/bin/phpcpd
  #PHPLOC
- wget https://phar.phpunit.de/phploc.phar
- chmod +x phploc.phar
- sudo mv phploc.phar /usr/local/bin/phploc
  #PDPdoc
  #- wget https://phpdoc.org/phpDocumentor.phar
  #- chmod +x phpDocumentor.phar
  #- sudo mv phpDocumentor.phar /usr/local/bin/phpdoc
before_script:
- echo "Zusätzliche Repositories werden geladen..."
- git clone https://github.com/jpbm04/travis-ci.git
- mv travis-ci build
- mkdir -p build/temp/extensions
- cd build/temp/extensions
- git clone https://github.com/jpbm04/organizer-com_thm_organizer.git
- git clone https://github.com/jpbm04/organizer-mod_thm_organizer_search.git 
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_content.git
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_subjects.git
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_groups.git
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_user.git
- cd ../../..
- cp build/config/configuration.php.dist configuration.php
- cp build/config/ext-install.xml.dist ext-install.xml
- echo "OK! Zusätzliche Repositories wurden geladen."
- build/scripts/shell/git-clean.sh "build/temp/extensions"

script:
- composer --version
- build/scripts/shell/init.sh

before_deploy:
        - build/scripts/shell/tag.sh

deploy:
  provider: releases
  api_key:
    secure: o2KqQTUFJwSR3K/ydyQZgNvlRS1rEiG0PT035ru6m042xBcSi+A4S2e3g+b3rjyQL/NpKPqSbaslSvMu7Xh8KD0AiM0CqyrfoOi8yjedJmDAEAk2MU+FKr0xeGpGNYwKEn8tjep4Q1hd3HNY4RnkuGGUnu7C+OBmIrfNZbGd9qPfV5UaCb5FDZCYSP8f75oUTiecve5lnH12xKetPy11p05PJPRGWjCL1A00cYrwMhvA7zVa40f0+Tf5/SE88398KTLvntLNUmAB8wCcCMwSmpWU1VGX1leG81AjBmGJ2fMyIoeUHowrC+Atw8OlUVL48izNkswYq/IAALR/IPH5+UxEkOUJh5CZl8qUZ5bSf7rb4mYgEdv94+3ajrZ0ODlQ2hh9IDwjvTkVEP2aIwYaAd6Wcv0uB4PdZjxKLTFyrrgVXYDWGyxLqxL5wq4Q7lQbMRxD5cinlyabc7KcVC8zo78dzAGUOuBTutJa5BQpiGaLJBBQeEKMZetCNhVgiAwViD+ZTgdu/CezNkSWfqpkRsd6ZL6p8JW3uFxQCrNzuO05/Vuj4Jqa3m/SqZH1YkM9qV0Xz78kR2RtkPjwKBMer8qqMfJZgq3YVnLG9vwkvAZgv7r86DSEramn9Yo2cF7gHpIdSM6Cen5DqG/io/iKMZiVLX6L0vEHTb/ZhFWoMmA=
  skip_cleanup: true
  overwrite: true
  prerelease: true
          #          condition: "${TRAVIS_TAG} =~ ^nightly-.*" #TODO: Benötigt wird invertiertes Suchmuster
  file_glob: true
  on:
          all_branches: true
          #condition: "${TRAVIS_TAG} =~ ^v[0-9].*"
  file:
          - archivedworkspace*.tar.gz
          - archivedextensions*.tar.gz
          - archivedbuildenviroment*.tar.gz
