language: php
php:
- 7.3
- 7.1
- 7.0
- nightly
stages:
- test
- ext
  #- release
jobs:
  include:
  - stage: ext
    name: Ext
    php: 7.3
    script: build/scripts/shell/ext.sh
  - stage: ext
    name: Ext
    php: 7.1
    script: build/scripts/shell/ext.sh
  - stage: ext
    name: Ext
    php: 7
    script: build/scripts/shell/ext.sh
  - stage: ext
    name: Ext
    php: nightly
    script: build/scripts/shell/ext.sh
    #  - stage: release
    #    name: Release
    #    script: build/scripts/shell/release.sh
matrix:
  allow_failures:
  - php: nightly
notifications:
  on_success: never
  on_failure: change
addons:
  apt:
    packages:
    - libxml2-utils
    - tree
services:
- mysql
before_install:
- npm install jshint
before_script:
- echo "Zusätzliche Repositories werden geladen..."
- git clone https://github.com/jpbm04/travis-ci.git || exit 1
- mv travis-ci build
- mkdir -p build/temp/extensions
- cd build/temp/extensions
- git clone https://github.com/jpbm04/organizer-com_thm_organizer-test.git || exit 1
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_subjects.git || exit 1
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_groups.git || exit 1
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_user.git || exit 1
- git clone https://github.com/jpbm04/organizer-plg_thm_organizer_search.git || exit 1
- cd ../../..
- cp build/config/configuration.php.dist configuration.php
- cp build/config/joomla.build.properties.dist joomla.build.properties
- cp build/config/ext-install.xml.dist ext-install.xml
- echo "OK! Zusätzliche Repositories wurden geladen."
script:
- build/scripts/shell/init.sh

after_success:
        - build/scripts/shell/release.sh

deploy:
  provider: releases
  api_key:
    secure: RKC5AcWZadZrVzJDzRp/prcJOFznLnv95ztRfqHhnhjfIPjk7imbWOYNV59/iU5jYPvAnk1w41r+mz3ieV0L3uYvYkclQm7qIdqGstkM5XHXDfDzx4poZNQpE0dSokBlN8inqEDeKl19MS0HU55cIjIPq+d/3oAX4WML/qXokBkIMX/0gaGI+QlAfctEI6hNs6J4qVIN3ri6fqhKOzs60wplIKoo/u21a5ddKeZvy9C/q9mpmjmDSnsvROoShCA9oaqLjTq7IYtVH9jrJpL70LsEfE5bKNRAZUNtfkQJ7pX/C2AXSDr12HFTZulknxlZpE9NQk/+xKhF9sWK/YEnSIdQMTejCvaOG1DeQKiHIOkTxgO85sltBMtl6aSiWPtijBKdTSLvPjSGQkr36LmBGZBHdxkAWkdXmVfG2Anr72Q275N58uVTJxKOf++TlKRWhszh+Ubnwx2xhOALtqRTZoCGjkQwwpq0iZ26ARJwn+5ol+/yGCqjwJwQj8BnNZtfUD1EuyXMbzSfrZtE8onk+1Gs3dK5fhCweFEKKxkKbFvqHv21tQaYYu3PKZglAN/pjxMaTwDHUOSoqV/5N03HKQp9rneAl8vsk6TOawwr6RwCAUCXdhYI5QsfMJ+WTp+j8fjGKSepKV+6S5Xvo6jIHVUwqTs2ai/AXdvCmmEXcHY=
  skip_cleanup: true
  prerelease: true
          #          condition: "${TRAVIS_TAG} =~ ^nightly-.*" #TODO: Dies ist bähbäh (Benötigt wird invertiertes Suchmuster)
  file_glob: true
  on:
          all_branches: true
          #condition: "${TRAVIS_TAG} =~ ^v[0-9].*"
  file:
          - archivedworkspace*.tar.gz
          - archivedextensions*.tar.gz
          - archivedbuildenviroment*.tar.gz
